-- PostgreSQL Inline Column PRIMARY KEY Test Cases

-- ============================================
-- BASIC INLINE PRIMARY KEY
-- ============================================

-- Simple INTEGER PRIMARY KEY
CREATE TABLE test_pk_int (
    id INTEGER PRIMARY KEY,
    name VARCHAR(100)
);

-- BIGINT PRIMARY KEY
CREATE TABLE test_pk_bigint (
    user_id BIGINT PRIMARY KEY,
    username VARCHAR(50)
);

-- VARCHAR PRIMARY KEY
CREATE TABLE test_pk_varchar (
    code VARCHAR(20) PRIMARY KEY,
    description TEXT
);

-- ============================================
-- PRIMARY KEY WITH SERIAL/IDENTITY
-- ============================================

-- SERIAL PRIMARY KEY
CREATE TABLE test_pk_serial (
    id SERIAL PRIMARY KEY,
    data VARCHAR(100)
);

-- BIGSERIAL PRIMARY KEY
CREATE TABLE test_pk_bigserial (
    id BIGSERIAL PRIMARY KEY,
    value VARCHAR(100)
);

-- SMALLSERIAL PRIMARY KEY
CREATE TABLE test_pk_smallserial (
    id SMALLSERIAL PRIMARY KEY,
    info TEXT
);

-- GENERATED ALWAYS AS IDENTITY
CREATE TABLE test_pk_identity_always (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(100)
);

-- GENERATED BY DEFAULT AS IDENTITY
CREATE TABLE test_pk_identity_default (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(100)
);

-- IDENTITY with options
CREATE TABLE test_pk_identity_options (
    id INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 100 INCREMENT BY 10) PRIMARY KEY,
    data TEXT
);

-- ============================================
-- PRIMARY KEY WITH NOT NULL
-- ============================================

-- PRIMARY KEY with explicit NOT NULL
CREATE TABLE test_pk_not_null (
    id INTEGER NOT NULL PRIMARY KEY,
    name VARCHAR(100)
);

-- ============================================
-- PRIMARY KEY WITH DIFFERENT DATA TYPES
-- ============================================

CREATE TABLE test_pk_uuid (
    id UUID PRIMARY KEY,
    data VARCHAR(100)
);

CREATE TABLE test_pk_text (
    code TEXT PRIMARY KEY,
    description VARCHAR(200)
);

CREATE TABLE test_pk_numeric (
    account_number NUMERIC(20,0) PRIMARY KEY,
    balance NUMERIC(12,2)
);

CREATE TABLE test_pk_date (
    event_date DATE PRIMARY KEY,
    event_name VARCHAR(100)
);

-- ============================================
-- PRIMARY KEY WITH DEFAULT
-- ============================================

-- PRIMARY KEY with DEFAULT
CREATE TABLE test_pk_default (
    id INTEGER PRIMARY KEY DEFAULT 1,
    name VARCHAR(100)
);

-- PRIMARY KEY with UUID default
CREATE TABLE test_pk_uuid_default (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    data TEXT
);

-- ============================================
-- EDGE CASES
-- ============================================

-- Multiple columns, one PRIMARY KEY
CREATE TABLE test_pk_multi_col (
    id INTEGER PRIMARY KEY,
    col1 VARCHAR(50),
    col2 INTEGER,
    col3 DATE
);

-- PRIMARY KEY with quoted identifiers
CREATE TABLE test_pk_quoted (
    "order-id" INTEGER PRIMARY KEY,
    order_date DATE
);

-- Schema-qualified table with PRIMARY KEY
CREATE SCHEMA IF NOT EXISTS hr;
CREATE TABLE hr.test_pk_schema (
    emp_id INTEGER PRIMARY KEY,
    emp_name VARCHAR(100)
);

-- PRIMARY KEY with CONSTRAINT name inline
CREATE TABLE test_pk_constraint_name (
    id INTEGER CONSTRAINT pk_test PRIMARY KEY,
    value TEXT
);
