-- PostgreSQL Data Types Test Cases

-- ============================================
-- INTEGER TYPES
-- ============================================

CREATE TABLE test_integer_types (
    col_smallint SMALLINT,
    col_integer INTEGER,
    col_int INT,
    col_bigint BIGINT
);

-- Serial types (auto-increment)
CREATE TABLE test_serial_types (
    col_smallserial SMALLSERIAL,
    col_serial SERIAL,
    col_bigserial BIGSERIAL
);

-- Identity columns (PostgreSQL 10+)
CREATE TABLE test_identity_types (
    col_identity_always INTEGER GENERATED ALWAYS AS IDENTITY,
    col_identity_default INTEGER GENERATED BY DEFAULT AS IDENTITY,
    col_identity_options INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 100 INCREMENT BY 10)
);

-- ============================================
-- NUMERIC TYPES
-- ============================================

CREATE TABLE test_numeric_types (
    col_numeric NUMERIC,
    col_numeric_precision NUMERIC(10,2),
    col_decimal DECIMAL(10,2)
);

-- Numeric with different precisions
CREATE TABLE test_numeric_precision (
    col_numeric_small NUMERIC(5,2),
    col_numeric_medium NUMERIC(10,4),
    col_numeric_large NUMERIC(20,8),
    col_numeric_max NUMERIC(1000,100)
);

-- ============================================
-- FLOATING POINT TYPES
-- ============================================

CREATE TABLE test_float_types (
    col_real REAL,
    col_double DOUBLE PRECISION,
    col_float8 FLOAT8,
    col_float4 FLOAT4
);

-- ============================================
-- MONETARY TYPE
-- ============================================

CREATE TABLE test_money (
    col_money MONEY
);

-- ============================================
-- CHARACTER TYPES
-- ============================================

CREATE TABLE test_character_types (
    col_char CHAR(10),
    col_character CHARACTER(10),
    col_varchar VARCHAR(255),
    col_character_varying CHARACTER VARYING(255),
    col_text TEXT
);

-- Character types with different lengths
CREATE TABLE test_char_lengths (
    col_char_1 CHAR(1),
    col_varchar_100 VARCHAR(100),
    col_varchar_max VARCHAR(65535)
);

-- ============================================
-- BINARY DATA TYPES
-- ============================================

CREATE TABLE test_binary_types (
    col_bytea BYTEA
);

-- ============================================
-- DATE AND TIME TYPES
-- ============================================

CREATE TABLE test_datetime_types (
    col_date DATE,
    col_time TIME,
    col_time_tz TIME WITH TIME ZONE,
    col_timestamp TIMESTAMP,
    col_timestamp_tz TIMESTAMP WITH TIME ZONE,
    col_timestamptz TIMESTAMPTZ,
    col_interval INTERVAL
);

-- DateTime with precision
CREATE TABLE test_datetime_precision (
    col_time_3 TIME(3),
    col_time_6 TIME(6),
    col_timestamp_3 TIMESTAMP(3),
    col_timestamp_6 TIMESTAMP(6),
    col_timestamptz_3 TIMESTAMPTZ(3)
);

-- ============================================
-- BOOLEAN TYPE
-- ============================================

CREATE TABLE test_boolean (
    col_bool BOOLEAN,
    col_bool_alt BOOL
);

-- ============================================
-- ENUM TYPE
-- ============================================

-- Create enum type
CREATE TYPE mood AS ENUM ('sad', 'ok', 'happy');
CREATE TYPE status_type AS ENUM ('pending', 'processing', 'completed', 'failed');

CREATE TABLE test_enum (
    col_mood mood,
    col_status status_type
);

-- ============================================
-- GEOMETRIC TYPES
-- ============================================

CREATE TABLE test_geometric_types (
    col_point POINT,
    col_line LINE,
    col_lseg LSEG,
    col_box BOX,
    col_path PATH,
    col_polygon POLYGON,
    col_circle CIRCLE
);

-- ============================================
-- NETWORK ADDRESS TYPES
-- ============================================

CREATE TABLE test_network_types (
    col_cidr CIDR,
    col_inet INET,
    col_macaddr MACADDR,
    col_macaddr8 MACADDR8
);

-- ============================================
-- BIT STRING TYPES
-- ============================================

CREATE TABLE test_bit_types (
    col_bit BIT,
    col_bit_1 BIT(1),
    col_bit_8 BIT(8),
    col_bit_varying BIT VARYING(64),
    col_varbit VARBIT(64)
);

-- ============================================
-- TEXT SEARCH TYPES
-- ============================================

CREATE TABLE test_textsearch_types (
    col_tsvector TSVECTOR,
    col_tsquery TSQUERY
);

-- ============================================
-- UUID TYPE
-- ============================================

CREATE TABLE test_uuid (
    col_uuid UUID
);

-- ============================================
-- JSON TYPES
-- ============================================

CREATE TABLE test_json_types (
    col_json JSON,
    col_jsonb JSONB
);

-- ============================================
-- ARRAY TYPES
-- ============================================

CREATE TABLE test_array_types (
    col_int_array INTEGER[],
    col_text_array TEXT[],
    col_varchar_array VARCHAR(100)[],
    col_int_array_2d INTEGER[][],
    col_int_array_sized INTEGER[5]
);

-- ============================================
-- RANGE TYPES
-- ============================================

CREATE TABLE test_range_types (
    col_int4range INT4RANGE,
    col_int8range INT8RANGE,
    col_numrange NUMRANGE,
    col_tsrange TSRANGE,
    col_tstzrange TSTZRANGE,
    col_daterange DATERANGE
);

-- ============================================
-- XML TYPE
-- ============================================

CREATE TABLE test_xml (
    col_xml XML
);

-- ============================================
-- COMPOSITE TYPES
-- ============================================

-- Create composite type
CREATE TYPE address AS (
    street VARCHAR(100),
    city VARCHAR(50),
    state VARCHAR(2),
    zip VARCHAR(10)
);

CREATE TABLE test_composite (
    id INTEGER PRIMARY KEY,
    home_address address,
    work_address address
);

-- ============================================
-- DOMAIN TYPES
-- ============================================

-- Create domain type
CREATE DOMAIN email_type AS VARCHAR(100) CHECK (VALUE ~ '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}$');
CREATE DOMAIN positive_int AS INTEGER CHECK (VALUE > 0);

CREATE TABLE test_domain (
    id INTEGER PRIMARY KEY,
    email email_type,
    quantity positive_int
);

-- ============================================
-- OID TYPES
-- ============================================

CREATE TABLE test_oid_types (
    col_oid OID,
    col_regproc REGPROC,
    col_regprocedure REGPROCEDURE,
    col_regoper REGOPER,
    col_regoperator REGOPERATOR,
    col_regclass REGCLASS,
    col_regtype REGTYPE
);

-- ============================================
-- PSEUDO TYPES
-- ============================================

CREATE TABLE test_pseudo_types (
    col_any "any",
    col_anyarray ANYARRAY
);

-- ============================================
-- COMPREHENSIVE DATA TYPES TABLE
-- ============================================

CREATE TABLE test_all_types (
    -- Integer types
    col_smallint SMALLINT,
    col_integer INTEGER,
    col_bigint BIGINT,
    col_serial SERIAL,

    -- Numeric types
    col_numeric NUMERIC(10,2),
    col_real REAL,
    col_double DOUBLE PRECISION,
    col_money MONEY,

    -- Character types
    col_char CHAR(50),
    col_varchar VARCHAR(255),
    col_text TEXT,

    -- Binary types
    col_bytea BYTEA,

    -- Date and time types
    col_date DATE,
    col_time TIME,
    col_timestamp TIMESTAMP,
    col_timestamptz TIMESTAMPTZ,
    col_interval INTERVAL,

    -- Boolean type
    col_boolean BOOLEAN,

    -- UUID
    col_uuid UUID,

    -- JSON types
    col_json JSON,
    col_jsonb JSONB,

    -- Array type
    col_int_array INTEGER[],

    -- Network types
    col_inet INET,
    col_macaddr MACADDR,

    -- Geometric types
    col_point POINT,
    col_polygon POLYGON
);
