CREATE
OR REPLACE TRANSIENT DATABASE TEST_DB COMMENT = 'test database with TRANSIENT storage type';

CREATE
OR REPLACE TRANSIENT SCHEMA TEST_DB.HP_TEST COMMENT = 'Use to test SNOWFLAKE DDL importer';

CREATE
OR REPLACE TRANSIENT TABLE TEST_DB.HP_TEST.CUSTOMERS (
  CUSTOMER_ID NUMBER(38, 0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
  FIRST_NAME VARCHAR(50),
  LAST_NAME VARCHAR(50),
  EMAIL VARCHAR(100),
  CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
  UNIQUE (EMAIL, FIRST_NAME, LAST_NAME),
  PRIMARY KEY (CUSTOMER_ID)
);

CREATE
OR REPLACE TRANSIENT TABLE TEST_DB.HP_TEST.ORDERS (
  ORDER_ID NUMBER(38, 0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
  CUSTOMER_ID NUMBER(38, 0),
  ORDER_DATE TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
  TOTAL_AMOUNT NUMBER(10, 2),
  PRIMARY KEY (ORDER_ID),
  FOREIGN KEY (CUSTOMER_ID) REFERENCES TEST_DB.HP_TEST.CUSTOMERS(CUSTOMER_ID)
);

CREATE
OR REPLACE TRANSIENT TABLE TEST_DB.HP_TEST.ORDER_ITEMS (
  ORDER_ITEM_ID NUMBER(38, 0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
  ORDER_ID NUMBER(38, 0),
  PRODUCT_ID NUMBER(38, 0),
  QUANTITY NUMBER(38, 0),
  PRICE NUMBER(10, 2),
  PRIMARY KEY (ORDER_ITEM_ID),
  FOREIGN KEY (ORDER_ID) REFERENCES TEST_DB.HP_TEST.ORDERS(ORDER_ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES TEST_DB.HP_TEST.PRODUCTS(PRODUCT_ID)
);

CREATE
OR REPLACE TRANSIENT TABLE TEST_DB.HP_TEST.PRODUCTS (
  PRODUCT_ID NUMBER(38, 0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
  PRODUCT_NAME VARCHAR(100),
  DESCRIPTION VARCHAR(16777216),
  PRICE NUMBER(10, 2),
  STOCK_QUANTITY NUMBER(38, 0),
  PRIMARY KEY (PRODUCT_ID)
);

CREATE
OR REPLACE TRANSIENT SCHEMA TEST_DB.PUBLIC;

CREATE
OR REPLACE TRANSIENT SCHEMA TEST_DB.TEST;

CREATE
OR REPLACE TRANSIENT TABLE TEST_DB.TEST."_holistics_persisted_test_20240703094645" (
  "a" NUMBER(1, 0),
  "b" NUMBER(1, 0),
  "c" NUMBER(1, 0)
);

CREATE
OR REPLACE TRANSIENT SCHEMA TEST_DB.TEST_2024_06_05_06_33_IZJGOY;

CREATE
OR REPLACE TRANSIENT SCHEMA TEST_DB.TEST_2024_06_11_11_08_YIEA7S;

CREATE
OR REPLACE TRANSIENT SCHEMA TEST_DB.TEST_2024_06_12_05_55_UNUEMX;

CREATE
OR REPLACE TRANSIENT SCHEMA TEST_DB.TEST_2024_06_19_03_15_DE01TD;

CREATE
OR REPLACE TRANSIENT SCHEMA TEST_DB.TEST_2024_06_28_10_01_ZQMIMY;

CREATE
OR REPLACE TRANSIENT TABLE TEST_DB.TEST_2024_06_28_10_01_ZQMIMY."ONE" (
  FOO VARCHAR(16777216),
  BAR VARCHAR(16777216),
  CONSTRAINT PKEY_FOO PRIMARY KEY (FOO),
  CONSTRAINT UNIQUE_BAR UNIQUE (BAR),
  CONSTRAINT UNIQUE_FOO_BAR UNIQUE (FOO, BAR),
  CONSTRAINT UNIQUE_BAR_FOO UNIQUE (BAR, FOO)
);

CREATE
OR REPLACE TRANSIENT TABLE TEST_DB.TEST_2024_06_28_10_01_ZQMIMY.TWO (
  ABC VARCHAR(16777216),
  XYZ VARCHAR(16777216),
  QWE VARCHAR(16777216),
  CONSTRAINT FKEY_ABC_XYZ FOREIGN KEY (XYZ, ABC) REFERENCES TEST_DB.TEST_2024_06_28_10_01_ZQMIMY."ONE"(BAR, FOO),
  CONSTRAINT FKEY_QWE FOREIGN KEY (QWE) REFERENCES TEST_DB.TEST_2024_06_28_10_01_ZQMIMY."ONE"(FOO),
  CONSTRAINT UNIQUE_QWE_ABC UNIQUE (QWE, ABC)
);

CREATE
OR REPLACE TRANSIENT SCHEMA TEST_DB.TEST_2024_07_03_09_46_3ARLDM;