CREATE TABLE table1 (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payload text
);

CREATE TABLE table2 (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar
);

CREATE TABLE table3 (
    id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar
);

CREATE TABLE table4 (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar
);
CREATE TABLE table5 (
    id serial PRIMARY KEY,
    name varchar
);
CREATE TABLE table6 (
    id smallserial PRIMARY KEY,
    name varchar
);
CREATE TABLE table7 (
    id bigserial PRIMARY KEY,
    name varchar
);

CREATE TABLE table8 (
    id Int GeNERaTED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar
);

CREATE TABLE table9 (
    id Intdsfsd GeNERaTED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar
);