-- Oracle SQL Inline GENERATED BY DEFAULT AS IDENTITY Test Cases
-- Test setup: Create tables with inline GENERATED BY DEFAULT AS IDENTITY constraints on different columns
CREATE TABLE customers (
    cust_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    cust_name VARCHAR2(100) DEFAULT 'Unknown',
    email VARCHAR2(100) DEFAULT 'noemail@example.com',
    phone VARCHAR2(20) DEFAULT 'N/A'
);

CREATE TABLE inventory (
    item_id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1),
    item_name VARCHAR2(200) DEFAULT 'Default Item',
    price NUMBER(10,2) DEFAULT 0.00,
    category VARCHAR2(50) DEFAULT 'Misc'
);

CREATE TABLE shipments (
    ship_id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 10),
    customer_id NUMBER(10) DEFAULT 1,
    ship_date DATE DEFAULT SYSDATE,
    total_amount NUMBER(12,2) DEFAULT 0.00
);

CREATE TABLE departments (
    dept_id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 2),
    dept_name VARCHAR2(100) DEFAULT 'General',
    manager_id NUMBER(10) DEFAULT 0,
    budget NUMBER(12,2) DEFAULT 10000.00
);

CREATE TABLE suppliers (
    supp_id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 500 INCREMENT BY 5),
    supp_name VARCHAR2(100) DEFAULT 'Anonymous',
    contact VARCHAR2(100) DEFAULT 'Contact',
    credit_limit NUMBER(10,2) DEFAULT 5000.00
);

CREATE TABLE test_datatypes (
    col_number NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 10 INCREMENT BY 1),
    col_varchar2 VARCHAR2(100) DEFAULT 'Default Text',
    col_char CHAR(10) DEFAULT 'DEFAULT   ',
    col_date DATE DEFAULT SYSDATE
);

-- ============================================
-- BASIC INLINE IDENTITY CONSTRAINTS
-- ============================================

-- Simple GENERATED BY DEFAULT AS IDENTITY
CREATE TABLE test_basic (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    value NUMBER(10) DEFAULT 100
);

-- IDENTITY with default settings
CREATE TABLE test_status (
    status_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    status VARCHAR2(20) DEFAULT 'OPEN'
);

-- IDENTITY with NOT NULL
CREATE TABLE test_not_null (
    record_id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR2(200) DEFAULT 'No description' NOT NULL
);

-- ============================================
-- IDENTITY WITH CUSTOM OPTIONS
-- ============================================

-- IDENTITY with START WITH
CREATE TABLE test_start_with (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
    order_code VARCHAR2(20) DEFAULT 'ORD000'
);

-- IDENTITY with INCREMENT BY
CREATE TABLE test_increment (
    ticket_id NUMBER GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY 5),
    ticket_type VARCHAR2(20) DEFAULT 'STANDARD'
);

-- IDENTITY with MAXVALUE
CREATE TABLE test_maxvalue (
    ref_id NUMBER GENERATED BY DEFAULT AS IDENTITY (MAXVALUE 99999),
    ref_name VARCHAR2(100) DEFAULT 'Reference'
);

-- IDENTITY with MINVALUE
CREATE TABLE test_minvalue (
    batch_id NUMBER GENERATED BY DEFAULT AS IDENTITY (MINVALUE 1),
    batch_name VARCHAR2(50) DEFAULT 'Batch'
);
