CREATE TABLE "table1" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "payload" text
);

CREATE TABLE "table2" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "table3" (
  "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "table4" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "table5" (
  "id" SERIAL PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "table6" (
  "id" SMALLSERIAL PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "table7" (
  "id" BIGSERIAL PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "table8" (
  "id" SERIAL PRIMARY KEY,
  "name" varchar
);
