CREATE TABLE "user" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" int,
  "address" "varcharacter"
);

CREATE TABLE "user1" (
  "id" SMALLSERIAL PRIMARY KEY,
  "name" int,
  "address" "varcharacter"
);

CREATE TABLE "user2" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" int,
  "address" "varcharacter"
);

CREATE TABLE "user3" (
  "id" SMALLSERIAL PRIMARY KEY,
  "name" int,
  "address" "varcharacter"
);

CREATE TABLE "user4" (
  "id" SERIAL PRIMARY KEY,
  "name" int,
  "address" "varcharacter"
);
