CREATE TABLE orders (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER UNIQUE NOT NULL,
  status VARCHAR2(50),
  created_at VARCHAR2(50),
  modified_at TIMESTAMP
);

CREATE TABLE order_items (
  order_id NUMBER,
  product_id NUMBER,
  quantity NUMBER DEFAULT 1,
  created_at TIMESTAMP WITH TIME ZONE,
  modified_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE users (
  id NUMBER PRIMARY KEY,
  full_name VARCHAR2(255),
  email VARCHAR2(255) UNIQUE,
  gender VARCHAR2(10),
  date_of_birth VARCHAR2(20),
  created_at VARCHAR2(30),
  modified_at TIMESTAMP(2),
  country_code NUMBER
);

CREATE TABLE merchants (
  id NUMBER PRIMARY KEY,
  merchant_name VARCHAR2(255),
  country_code NUMBER,
  created_at VARCHAR2(30),
  modified_at TIMESTAMP,
  admin_id NUMBER
);

CREATE TABLE countries (
  code NUMBER PRIMARY KEY,
  name VARCHAR2(100),
  continent_name VARCHAR2(100)
);


ALTER TABLE users ADD FOREIGN KEY (country_code) REFERENCES countries (code);

ALTER TABLE merchants ADD FOREIGN KEY (country_code) REFERENCES countries (code);

CREATE TABLE accounts (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  domain VARCHAR2(100),
  name VARCHAR2(100),
  slug VARCHAR2(10)
);

CREATE TABLE tests (
  id NUMBER(19,0) NOT NULL,
  type VARCHAR2(100) DEFAULT 'testing'
);

--not work
CREATE TABLE users2 (
    username VARCHAR2(255) NOT NULL,
    hashed_password VARCHAR2(255) NOT NULL,
    full_name VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) NOT NULL,
    --password_changed_at TIMESTAMP WITH TIME ZONE DEFAULT TIMESTAMP '0001-01-01 00:00:00 +00:00' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE table1 (
    field VARCHAR2(200) NOT NULL,
    field2 VARCHAR2(200) NOT NULL,
    CONSTRAINT table1_pk PRIMARY KEY (field, field2)
);

CREATE TABLE table2 (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field VARCHAR2(200),
    field2 VARCHAR2(200),
    CONSTRAINT table2_fk FOREIGN KEY (field) REFERENCES table1(field)
);
