ALTER TABLE name
    RENAME CONSTRAINT constraint_name TO new_constraint_name;

ALTER TABLE name
    RENAME TO new_name;

ALTER TABLE name
    ADD column_name data_type,
    DROP COLUMN column_name,
    MODIFY (column_name data_type NOT NULL),
    MODIFY (column_name data_type NULL);

CREATE VIEW view_name AS
    SELECT *
    FROM table_name;

DROP VIEW view_name;

SELECT *
FROM table_name
WHERE column_name = 'test';

SELECT *
FROM table_name
WHERE column_name = 'test'
ORDER BY column_name;

SELECT COUNT(*)
FROM table_name;

CREATE TABLE table_name(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
); --only statement that should not be ignored and should be visualised by DBML

DROP TABLE table_name;

DROP INDEX index_name;

INSERT INTO table_name (column1, column2)
VALUES (value1, value2);
