name: Bearer PR Check

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  rule_check:
    runs-on: ubuntu-22.04
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: Run Report
        id: report
        uses: bearer/bearer-action@v2
        with:
          format: rdjson
          output: rd.json
          config-file: 'bearer.yml'
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Run reviewdog
        env:
          REVIEWDOG_TOKEN: ${{ secrets.REVIEWDOG_TOKEN }}
        run:
          cat rd.json | reviewdog -f=rdjson -reporter=github-pr-check -filter-mode=added -fail-on-error=false